# Generated by Django 5.1 on 2024-09-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.TextField(max_length=200, verbose_name='Nombre del Producto')),
                ('Marca', models.TextField(max_length=200, verbose_name='Marca del producto')),
                ('Presentacion', models.TextField(max_length=200, verbose_name='Presentacion')),
                ('Descripcion', models.TextField(max_length=300, verbose_name='Descripcion del Producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (COP)')),
                ('Disponible', models.BooleanField(default=True, verbose_name='Disponibles')),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Foto Producto')),
            ],
        ),
    ]
