# Generated by Django 5.1 on 2024-09-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='Nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del Producto'),
        ),
    ]
